// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiqFCLWS6dXAHqDWVaBP_NevlGMCmeQEI',
    appId: '1:352155153951:web:1b6d06ffccac270852472a',
    messagingSenderId: '352155153951',
    projectId: 'muvee-app',
    authDomain: 'muvee-app.firebaseapp.com',
    storageBucket: 'muvee-app.firebasestorage.app',
    measurementId: 'G-KDZXPFX2P6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6ZBpaFRxTV_jA86jtUTRoxfFP3HdoC7k',
    appId: '1:352155153951:android:3500a7f8a5899b4b52472a',
    messagingSenderId: '352155153951',
    projectId: 'muvee-app',
    storageBucket: 'muvee-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUTppTojXJVennx12tfHOuZbuM2nvtaXo',
    appId: '1:352155153951:ios:eb71ce2bd4402a1f52472a',
    messagingSenderId: '352155153951',
    projectId: 'muvee-app',
    storageBucket: 'muvee-app.firebasestorage.app',
    iosBundleId: 'com.example.muveeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUTppTojXJVennx12tfHOuZbuM2nvtaXo',
    appId: '1:352155153951:ios:eb71ce2bd4402a1f52472a',
    messagingSenderId: '352155153951',
    projectId: 'muvee-app',
    storageBucket: 'muvee-app.firebasestorage.app',
    iosBundleId: 'com.example.muveeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiqFCLWS6dXAHqDWVaBP_NevlGMCmeQEI',
    appId: '1:352155153951:web:40964b6522481c4352472a',
    messagingSenderId: '352155153951',
    projectId: 'muvee-app',
    authDomain: 'muvee-app.firebaseapp.com',
    storageBucket: 'muvee-app.firebasestorage.app',
    measurementId: 'G-7N23686LTE',
  );
}
